version: "3.7"
services:
  webserver:
    build: .
    command: ["magellan", "webserver"]
    ports:
      - 8080:8080
    volumes:
      - ./:/root/webserver
      - ~/.aws:/root/.aws
    environment:
      - FLASK_DEBUG=1
      - MAGELLAN__ELASTICSEARCH_URL=elasticsearch:9200
      - MAGELLAN__SQLALCHEMY_CONN_STRING=postgresql+psycopg2://magellan:magellan@db/magellan
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=magellan
      - POSTGRES_PASSWORD=magellan
      - POSTGRES_DB=magellan
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.12
    ports:
      - 9200:9200
volumes:
  postgres_data:
