"""empty message

Revision ID: f05e2340143e
Revises: f17210d52107
Create Date: 2020-10-27 01:38:55.146136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f05e2340143e"
down_revision = "f17210d52107"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles_data_source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data_source", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["data_source"],
            ["data_source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["ab_role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "roles_dataset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset"],
            ["dataset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["ab_role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("roles_dataset")
    op.drop_table("roles_data_source")
    # ### end Alembic commands ###
